name: Convert Images Automatically

on:
  push:
    branches:
      - main        # mainブランチにpushされたとき実行
    paths:
      - 'data/Products/**' # images/フォルダ内に変更があったときだけ

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm init -y
          npm install sharp

      - name: Convert images
        run: |
          mkdir -p dist/images
          node -e "
          import fs from 'fs'; import sharp from 'sharp';
          const files = fs.readdirSync('images');
          fs.mkdirSync('dist/images', {recursive:true});
          for (const f of files) {
            const name = f.split('.')[0];
            sharp('images/'+f).webp({quality:80}).toFile('dist/images/'+name+'.webp');
          }"

      - name: Commit and push results
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add dist/images -f
          git commit -m 'Auto convert images' || echo 'No changes'
          git push
