name: Convert Images to WebP

on:
  push:
    branches:
      - main
    paths:
      - "data/Products/**" # Products フォルダ内に変更があったら実行

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      # ① リポジトリを取得
      - name: Checkout repository
        uses: actions/checkout@v4

      # ② Node.js をセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # ③ sharp をインストール
      - name: Install sharp
        run: |
          npm init -y
          npm install sharp

      # ④ WebP 変換を実行
      - name: Convert to WebP
        run: |
          mkdir -p data/WEBPimages
          node -e "
          import fs from 'fs';
          import path from 'path';
          import sharp from 'sharp';
          const inputDir = 'data/Products';
          const outputDir = 'data/WEBPimages';
          fs.mkdirSync(outputDir, { recursive: true });
          const files = fs.readdirSync(inputDir);
          for (const file of files) {
            const ext = path.extname(file).toLowerCase();
            if (!['.jpg', '.jpeg', '.png'].includes(ext)) continue;
            const base = path.parse(file).name;
            sharp(path.join(inputDir, file))
              .webp({ quality: 80 })
              .toFile(path.join(outputDir, base + '.webp'))
              .then(() => console.log('✅ Converted:', file))
              .catch(err => console.error('❌ Error:', err));
          }"

      # ⑤ 結果をコミット & push
      - name: Commit and push converted images
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GHPAT }}@github.com/tkorigami16-lab/TKoriken.git
          git push origin main
